### ISSUE TITLE
Parse Error when using the "-e" flag with  MCBooster_Example_CUDA_GenerateSample

### ISSUE THREAD

**Issue by hassec** [MultithreadCorner/MCBooster#1]
Followed the installation steps provided and compiled with:
NVCC V7.5.17
Cuda architecture 2.1(2.0)
gcc 4.8.5

All examples seem to run without a problem.
The only error I observed so far is the following:

PARSE ERROR: Argument: -e1000
             Couldn't find match for argument

when trying to use the -e flag with the binary "MCBooster_Example_CUDA_GenerateSample"

**Comment by hassec** [comment]
Ok... stupid mistake on my part.
You obviously have to leave space between -e and the number.
This works: 
./MCBooster_Example_CUDA_GenerateSample -m "1.865;0.439;0.139;0.139" -p 'D0;K;pip;pim' -e 10000

**Comment by AAAlvesJr** [comment]
I realized it later also. I changed that code, now to avoid problems, it will be necessary to add '=' between the flag and its value. The updated version will be available here soon, together with other improvements on the examples. By the way, thanks for the interest.
