### ISSUE TITLE
unnecessary If statement in EvaluateArray?

### ISSUE THREAD

**Issue by hassec** [MultithreadCorner/MCBooster#5]
If I am not mistaken, can't we get ride of [these](https://github.com/MultithreadCorner/MCBooster/blob/e607d4c8c31d7dc16772d1c02f4c8c022348830a/mcbooster/EvaluateArray.h#L564-L574) lines?

The If statement on line 322 makes sure that this only run for device -> device evaluation. So no need for the lines linked to above right?

**Comment by AAAlvesJr** [comment]
Actually you are mistaken. If the device is a gpu, we can evaluate on device and keep results on device or bring than to host. So we need the if statement.

**Comment by LLyq17** [comment]
Error generating file
           Dears. when I compile  using make <command> .The error shows below:

`18 errors detected in the compilation of "/tmp/tmpxft_0000b08b_00000000-6_Generate.cpp1.ii".
-- Removing /home/lq/Downloads/MCBooster/build/CMakeFiles/MCBooster_Example_CUDA_B2KPiJpsi.dir/src/./MCBooster_Example_CUDA_B2KPiJpsi_generated_Generate.cu.o
/usr/bin/cmake -E remove /home/lq/Downloads/MCBooster/build/CMakeFiles/MCBooster_Example_CUDA_B2KPiJpsi.dir/src/./MCBooster_Example_CUDA_B2KPiJpsi_generated_Generate.cu.o
CMake Error at MCBooster_Example_CUDA_B2KPiJpsi_generated_Generate.cu.o.cmake:264 (message):
  Error generating file
  /home/lq/Downloads/MCBooster/build/CMakeFiles/MCBooster_Example_CUDA_B2KPiJpsi.dir/src/./MCBooster_Example_CUDA_B2KPiJpsi_generated_Generate.cu.o


make[2]: *** [CMakeFiles/MCBooster_Example_CUDA_B2KPiJpsi.dir/src/./MCBooster_Example_CUDA_B2KPiJpsi_generated_Generate.cu.o] Error 1
make[2]: Leaving directory `/home/lq/Downloads/MCBooster/build'
make[1]: *** [CMakeFiles/MCBooster_Example_CUDA_B2KPiJpsi.dir/all] Error 2
make[1]: Leaving directory `/home/lq/Downloads/MCBooster/build'
make: *** [all] Error 2
`
How to solve this problem in the process of install.thank you!
