### ISSUE TITLE
The usage of fseed doesn't really produce uncorrelated sets of rnd numbers.

### ISSUE THREAD

**Issue by hassec** [MultithreadCorner/MCBooster#7]
Hi,

let me try to explain what I mean: 
So when using mcbooster to generate large amounts of random numbers you will need to do it in batches since a GPU has limited memory right? But if you use different seeds, in MCBoster it doesn't really change that much. See here: https://github.com/MultithreadCorner/MCBooster/blob/master/mcbooster/functors/DecayMother.h#L150

The number of collisions depend on the number of events generated. (They grow approx. quadratic)
I propose using an offset rather than the multiplication by "fseed", thus starting at  "evt+offset" if I generate a second batch of numbers.

Hope this is somewhat understandable. If not I'll be happy to clearify this more.
Cheers

**Comment by AAAlvesJr** [comment]
Issue addressed in the latest dev release.
